---
name: Build and push

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 2 * * 0"

jobs:
  build-and-push:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        include:
          - context: 2
            tags: |
              ${{ github.repository }}:2
              ghcr.io/${{ github.repository }}:2
          - context: 2023
            tags: |
              ${{ github.repository }}:2023
              ghcr.io/${{ github.repository }}:2023
              ${{ github.repository }}:latest
              ghcr.io/${{ github.repository }}:latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.context }}
          file: ./${{ matrix.context }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.tags }}
